export const MOCK_DEBATES = [
  {
    id: 1,
    title: "Should student loans be forgiven for all borrowers?",
    source: "NYTimes",
    leaning: "Democrat",
    mediaType: "article",
    canonicalUrl: "https://www.nytimes.com/2026/01/14/us/student-loan-forgiveness-policy.html",
    sourceFeedUrl: "https://rss.nytimes.com/services/xml/rss/nyt/US.xml",
    sourceItemId: "nyt:us:student-loan-forgiveness-policy",
    publishedAt: Date.now() - 1000 * 60 * 60 * 6,
  },
  {
    id: 2,
    title: "Is TikTok a national security threat?",
    source: "Fox News",
    leaning: "Conservative",
    mediaType: "article",
    canonicalUrl: "https://www.foxnews.com/politics/tiktok-national-security-threat-lawmakers",
    sourceFeedUrl: "https://feeds.foxnews.com/foxnews/politics",
    sourceItemId: "fox:politics:tiktok-national-security-threat-lawmakers",
    publishedAt: Date.now() - 1000 * 60 * 60 * 5,
  },
  {
    id: 3,
    title: "Who is politics biggest inside trader?",
    source: "Fox News",
    leaning: "Conservative",
    mediaType: "video",
    canonicalUrl: "https://www.foxnews.com/video/inside-trading-congress-analysis",
    sourceFeedUrl: "https://feeds.foxnews.com/foxnews/politics",
    sourceItemId: "fox:video:inside-trading-congress-analysis",
    publishedAt: Date.now() - 1000 * 60 * 60 * 4,
  },
  {
    id: 4,
    title: "Is MGT right to leave congress?",
    source: "CNN",
    leaning: "Democrat",
    mediaType: "article",
    canonicalUrl: "https://www.cnn.com/2026/01/14/politics/mgt-leave-congress-analysis/index.html",
    sourceFeedUrl: "http://rss.cnn.com/rss/cnn_allpolitics.rss",
    sourceItemId: "cnn:politics:mgt-leave-congress-analysis",
    publishedAt: Date.now() - 1000 * 60 * 60 * 3,
  },
  {
    id: 5,
    title: "Why is the griddy so influential",
    source: "CNN",
    leaning: "Democrat",
    mediaType: "video",
    canonicalUrl: "https://www.cnn.com/2026/01/14/sport/griddy-influence-explainer/index.html",
    sourceFeedUrl: "http://rss.cnn.com/rss/cnn_sport.rss",
    sourceItemId: "cnn:sport:griddy-influence-explainer",
    publishedAt: Date.now() - 1000 * 60 * 60 * 2,
  },

  // --- more “bot-ingestion realistic” items ---

  {
    id: 6,
    title: "Congress renews push to ban stock trading by lawmakers",
    source: "Reuters",
    leaning: "Conservative",
    mediaType: "article",
    canonicalUrl: "https://www.reuters.com/world/us/congress-renews-push-ban-stock-trading-lawmakers-2026-01-14/",
    sourceFeedUrl: "https://www.reuters.com/my-news/feed/",
    sourceItemId: "reuters:us:congress-ban-lawmakers-stock-trading:2026-01-14",
    publishedAt: Date.now() - 1000 * 60 * 60 * 9,
  },
  {
    id: 7,
    title: "Regulators outline new rules aimed at AI transparency",
    source: "The Verge",
    leaning: "Democrat",
    mediaType: "article",
    canonicalUrl: "https://www.theverge.com/2026/1/14/ai-transparency-rules-proposal",
    sourceFeedUrl: "https://www.theverge.com/rss/index.xml",
    sourceItemId: "verge:ai:transparency-rules-proposal",
    publishedAt: Date.now() - 1000 * 60 * 60 * 13,
  },
  {
    id: 8,
    title: "Tech companies debate encryption backdoors after new proposal",
    source: "NPR",
    leaning: "Democrat",
    mediaType: "podcast",
    canonicalUrl: "https://www.npr.org/2026/01/14/tech/encryption-backdoors-proposal",
    sourceFeedUrl: "http://www.npr.org/rss/rss.php?id=1019",
    sourceItemId: "npr:technology:encryption-backdoors-proposal",
    publishedAt: Date.now() - 1000 * 60 * 60 * 18,
  },
  {
    id: 9,
    title: "States expand tuition assistance as debate over free college grows",
    source: "AP News",
    leaning: "Democrat",
    mediaType: "article",
    canonicalUrl: "https://apnews.com/article/tuition-assistance-free-college-debate-2026",
    sourceFeedUrl: "https://apnews.com/index.rss",
    sourceItemId: "ap:education:tuition-assistance-free-college-debate",
    publishedAt: Date.now() - 1000 * 60 * 60 * 22,
  },
  {
    id: 10,
    title: "Border policy clash intensifies as lawmakers negotiate funding",
    source: "Reuters",
    leaning: "Conservative",
    mediaType: "article",
    canonicalUrl: "https://www.reuters.com/world/us/border-policy-clash-intensifies-lawmakers-negotiate-funding-2026-01-13/",
    sourceFeedUrl: "https://www.reuters.com/my-news/feed/",
    sourceItemId: "reuters:us:border-policy-funding:2026-01-13",
    publishedAt: Date.now() - 1000 * 60 * 60 * 28,
  },
];
